/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthOauthRouteImport } from './routes/auth/oauth'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as AppRulesetsIndexRouteImport } from './routes/_app/rulesets/index'
import { Route as AppProfilesIndexRouteImport } from './routes/_app/profiles/index'
import { Route as AppFactionsIndexRouteImport } from './routes/_app/factions/index'
import { Route as AppAssetsIndexRouteImport } from './routes/_app/assets/index'
import { Route as AppRulesetsCreateRouteImport } from './routes/_app/rulesets/create'
import { Route as AppRulesetsIdRouteImport } from './routes/_app/rulesets/$id'
import { Route as AppProfilesSettingsRouteImport } from './routes/_app/profiles/settings'
import { Route as AppProfilesSlugRouteImport } from './routes/_app/profiles/$slug'
import { Route as AppGroupsCreateRouteImport } from './routes/_app/groups/create'
import { Route as AppFactionsMineRouteImport } from './routes/_app/factions/mine'
import { Route as AppFactionsCreateRouteImport } from './routes/_app/factions/create'
import { Route as AppFactionsFactionIdRouteImport } from './routes/_app/factions/$factionId'
import { Route as AppAssetsCreateRouteImport } from './routes/_app/assets/create'
import { Route as AppAdminMigrationsRouteImport } from './routes/_app/admin/migrations'
import { Route as AppFactionsFactionIdSheetRouteImport } from './routes/_app/factions/$factionId/sheet'
import { Route as AppFactionsFactionIdEditRouteImport } from './routes/_app/factions/$factionId/edit'
import { Route as AppRulesetsRulesetSlugFaqQuestionSlugRouteImport } from './routes/_app/rulesets/$rulesetSlug/faq/$questionSlug'
import { Route as AppRulesetsIdFaqCreateRouteImport } from './routes/_app/rulesets/$id/faq/create'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthOauthRoute = AuthOauthRouteImport.update({
  id: '/auth/oauth',
  path: '/auth/oauth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRulesetsIndexRoute = AppRulesetsIndexRouteImport.update({
  id: '/rulesets/',
  path: '/rulesets/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilesIndexRoute = AppProfilesIndexRouteImport.update({
  id: '/profiles/',
  path: '/profiles/',
  getParentRoute: () => AppRoute,
} as any)
const AppFactionsIndexRoute = AppFactionsIndexRouteImport.update({
  id: '/factions/',
  path: '/factions/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsIndexRoute = AppAssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => AppRoute,
} as any)
const AppRulesetsCreateRoute = AppRulesetsCreateRouteImport.update({
  id: '/rulesets/create',
  path: '/rulesets/create',
  getParentRoute: () => AppRoute,
} as any)
const AppRulesetsIdRoute = AppRulesetsIdRouteImport.update({
  id: '/rulesets/$id',
  path: '/rulesets/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilesSettingsRoute = AppProfilesSettingsRouteImport.update({
  id: '/profiles/settings',
  path: '/profiles/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilesSlugRoute = AppProfilesSlugRouteImport.update({
  id: '/profiles/$slug',
  path: '/profiles/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsCreateRoute = AppGroupsCreateRouteImport.update({
  id: '/groups/create',
  path: '/groups/create',
  getParentRoute: () => AppRoute,
} as any)
const AppFactionsMineRoute = AppFactionsMineRouteImport.update({
  id: '/factions/mine',
  path: '/factions/mine',
  getParentRoute: () => AppRoute,
} as any)
const AppFactionsCreateRoute = AppFactionsCreateRouteImport.update({
  id: '/factions/create',
  path: '/factions/create',
  getParentRoute: () => AppRoute,
} as any)
const AppFactionsFactionIdRoute = AppFactionsFactionIdRouteImport.update({
  id: '/factions/$factionId',
  path: '/factions/$factionId',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsCreateRoute = AppAssetsCreateRouteImport.update({
  id: '/assets/create',
  path: '/assets/create',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminMigrationsRoute = AppAdminMigrationsRouteImport.update({
  id: '/admin/migrations',
  path: '/admin/migrations',
  getParentRoute: () => AppRoute,
} as any)
const AppFactionsFactionIdSheetRoute =
  AppFactionsFactionIdSheetRouteImport.update({
    id: '/sheet',
    path: '/sheet',
    getParentRoute: () => AppFactionsFactionIdRoute,
  } as any)
const AppFactionsFactionIdEditRoute =
  AppFactionsFactionIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppFactionsFactionIdRoute,
  } as any)
const AppRulesetsRulesetSlugFaqQuestionSlugRoute =
  AppRulesetsRulesetSlugFaqQuestionSlugRouteImport.update({
    id: '/rulesets/$rulesetSlug/faq/$questionSlug',
    path: '/rulesets/$rulesetSlug/faq/$questionSlug',
    getParentRoute: () => AppRoute,
  } as any)
const AppRulesetsIdFaqCreateRoute = AppRulesetsIdFaqCreateRouteImport.update({
  id: '/faq/create',
  path: '/faq/create',
  getParentRoute: () => AppRulesetsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/oauth': typeof AuthOauthRoute
  '/auth/': typeof AuthIndexRoute
  '/admin/migrations': typeof AppAdminMigrationsRoute
  '/assets/create': typeof AppAssetsCreateRoute
  '/factions/$factionId': typeof AppFactionsFactionIdRouteWithChildren
  '/factions/create': typeof AppFactionsCreateRoute
  '/factions/mine': typeof AppFactionsMineRoute
  '/groups/create': typeof AppGroupsCreateRoute
  '/profiles/$slug': typeof AppProfilesSlugRoute
  '/profiles/settings': typeof AppProfilesSettingsRoute
  '/rulesets/$id': typeof AppRulesetsIdRouteWithChildren
  '/rulesets/create': typeof AppRulesetsCreateRoute
  '/assets/': typeof AppAssetsIndexRoute
  '/factions/': typeof AppFactionsIndexRoute
  '/profiles/': typeof AppProfilesIndexRoute
  '/rulesets/': typeof AppRulesetsIndexRoute
  '/factions/$factionId/edit': typeof AppFactionsFactionIdEditRoute
  '/factions/$factionId/sheet': typeof AppFactionsFactionIdSheetRoute
  '/rulesets/$id/faq/create': typeof AppRulesetsIdFaqCreateRoute
  '/rulesets/$rulesetSlug/faq/$questionSlug': typeof AppRulesetsRulesetSlugFaqQuestionSlugRoute
}
export interface FileRoutesByTo {
  '/auth/error': typeof AuthErrorRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/oauth': typeof AuthOauthRoute
  '/': typeof AppIndexRoute
  '/auth': typeof AuthIndexRoute
  '/admin/migrations': typeof AppAdminMigrationsRoute
  '/assets/create': typeof AppAssetsCreateRoute
  '/factions/$factionId': typeof AppFactionsFactionIdRouteWithChildren
  '/factions/create': typeof AppFactionsCreateRoute
  '/factions/mine': typeof AppFactionsMineRoute
  '/groups/create': typeof AppGroupsCreateRoute
  '/profiles/$slug': typeof AppProfilesSlugRoute
  '/profiles/settings': typeof AppProfilesSettingsRoute
  '/rulesets/$id': typeof AppRulesetsIdRouteWithChildren
  '/rulesets/create': typeof AppRulesetsCreateRoute
  '/assets': typeof AppAssetsIndexRoute
  '/factions': typeof AppFactionsIndexRoute
  '/profiles': typeof AppProfilesIndexRoute
  '/rulesets': typeof AppRulesetsIndexRoute
  '/factions/$factionId/edit': typeof AppFactionsFactionIdEditRoute
  '/factions/$factionId/sheet': typeof AppFactionsFactionIdSheetRoute
  '/rulesets/$id/faq/create': typeof AppRulesetsIdFaqCreateRoute
  '/rulesets/$rulesetSlug/faq/$questionSlug': typeof AppRulesetsRulesetSlugFaqQuestionSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth/error': typeof AuthErrorRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/oauth': typeof AuthOauthRoute
  '/_app/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_app/admin/migrations': typeof AppAdminMigrationsRoute
  '/_app/assets/create': typeof AppAssetsCreateRoute
  '/_app/factions/$factionId': typeof AppFactionsFactionIdRouteWithChildren
  '/_app/factions/create': typeof AppFactionsCreateRoute
  '/_app/factions/mine': typeof AppFactionsMineRoute
  '/_app/groups/create': typeof AppGroupsCreateRoute
  '/_app/profiles/$slug': typeof AppProfilesSlugRoute
  '/_app/profiles/settings': typeof AppProfilesSettingsRoute
  '/_app/rulesets/$id': typeof AppRulesetsIdRouteWithChildren
  '/_app/rulesets/create': typeof AppRulesetsCreateRoute
  '/_app/assets/': typeof AppAssetsIndexRoute
  '/_app/factions/': typeof AppFactionsIndexRoute
  '/_app/profiles/': typeof AppProfilesIndexRoute
  '/_app/rulesets/': typeof AppRulesetsIndexRoute
  '/_app/factions/$factionId/edit': typeof AppFactionsFactionIdEditRoute
  '/_app/factions/$factionId/sheet': typeof AppFactionsFactionIdSheetRoute
  '/_app/rulesets/$id/faq/create': typeof AppRulesetsIdFaqCreateRoute
  '/_app/rulesets/$rulesetSlug/faq/$questionSlug': typeof AppRulesetsRulesetSlugFaqQuestionSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/error'
    | '/auth/login'
    | '/auth/oauth'
    | '/auth/'
    | '/admin/migrations'
    | '/assets/create'
    | '/factions/$factionId'
    | '/factions/create'
    | '/factions/mine'
    | '/groups/create'
    | '/profiles/$slug'
    | '/profiles/settings'
    | '/rulesets/$id'
    | '/rulesets/create'
    | '/assets/'
    | '/factions/'
    | '/profiles/'
    | '/rulesets/'
    | '/factions/$factionId/edit'
    | '/factions/$factionId/sheet'
    | '/rulesets/$id/faq/create'
    | '/rulesets/$rulesetSlug/faq/$questionSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/error'
    | '/auth/login'
    | '/auth/oauth'
    | '/'
    | '/auth'
    | '/admin/migrations'
    | '/assets/create'
    | '/factions/$factionId'
    | '/factions/create'
    | '/factions/mine'
    | '/groups/create'
    | '/profiles/$slug'
    | '/profiles/settings'
    | '/rulesets/$id'
    | '/rulesets/create'
    | '/assets'
    | '/factions'
    | '/profiles'
    | '/rulesets'
    | '/factions/$factionId/edit'
    | '/factions/$factionId/sheet'
    | '/rulesets/$id/faq/create'
    | '/rulesets/$rulesetSlug/faq/$questionSlug'
  id:
    | '__root__'
    | '/_app'
    | '/auth/error'
    | '/auth/login'
    | '/auth/oauth'
    | '/_app/'
    | '/auth/'
    | '/_app/admin/migrations'
    | '/_app/assets/create'
    | '/_app/factions/$factionId'
    | '/_app/factions/create'
    | '/_app/factions/mine'
    | '/_app/groups/create'
    | '/_app/profiles/$slug'
    | '/_app/profiles/settings'
    | '/_app/rulesets/$id'
    | '/_app/rulesets/create'
    | '/_app/assets/'
    | '/_app/factions/'
    | '/_app/profiles/'
    | '/_app/rulesets/'
    | '/_app/factions/$factionId/edit'
    | '/_app/factions/$factionId/sheet'
    | '/_app/rulesets/$id/faq/create'
    | '/_app/rulesets/$rulesetSlug/faq/$questionSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthErrorRoute: typeof AuthErrorRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOauthRoute: typeof AuthOauthRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/oauth': {
      id: '/auth/oauth'
      path: '/auth/oauth'
      fullPath: '/auth/oauth'
      preLoaderRoute: typeof AuthOauthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/rulesets/': {
      id: '/_app/rulesets/'
      path: '/rulesets'
      fullPath: '/rulesets/'
      preLoaderRoute: typeof AppRulesetsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profiles/': {
      id: '/_app/profiles/'
      path: '/profiles'
      fullPath: '/profiles/'
      preLoaderRoute: typeof AppProfilesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/factions/': {
      id: '/_app/factions/'
      path: '/factions'
      fullPath: '/factions/'
      preLoaderRoute: typeof AppFactionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets/': {
      id: '/_app/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AppAssetsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rulesets/create': {
      id: '/_app/rulesets/create'
      path: '/rulesets/create'
      fullPath: '/rulesets/create'
      preLoaderRoute: typeof AppRulesetsCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rulesets/$id': {
      id: '/_app/rulesets/$id'
      path: '/rulesets/$id'
      fullPath: '/rulesets/$id'
      preLoaderRoute: typeof AppRulesetsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profiles/settings': {
      id: '/_app/profiles/settings'
      path: '/profiles/settings'
      fullPath: '/profiles/settings'
      preLoaderRoute: typeof AppProfilesSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profiles/$slug': {
      id: '/_app/profiles/$slug'
      path: '/profiles/$slug'
      fullPath: '/profiles/$slug'
      preLoaderRoute: typeof AppProfilesSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/create': {
      id: '/_app/groups/create'
      path: '/groups/create'
      fullPath: '/groups/create'
      preLoaderRoute: typeof AppGroupsCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/factions/mine': {
      id: '/_app/factions/mine'
      path: '/factions/mine'
      fullPath: '/factions/mine'
      preLoaderRoute: typeof AppFactionsMineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/factions/create': {
      id: '/_app/factions/create'
      path: '/factions/create'
      fullPath: '/factions/create'
      preLoaderRoute: typeof AppFactionsCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/factions/$factionId': {
      id: '/_app/factions/$factionId'
      path: '/factions/$factionId'
      fullPath: '/factions/$factionId'
      preLoaderRoute: typeof AppFactionsFactionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets/create': {
      id: '/_app/assets/create'
      path: '/assets/create'
      fullPath: '/assets/create'
      preLoaderRoute: typeof AppAssetsCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/migrations': {
      id: '/_app/admin/migrations'
      path: '/admin/migrations'
      fullPath: '/admin/migrations'
      preLoaderRoute: typeof AppAdminMigrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/factions/$factionId/sheet': {
      id: '/_app/factions/$factionId/sheet'
      path: '/sheet'
      fullPath: '/factions/$factionId/sheet'
      preLoaderRoute: typeof AppFactionsFactionIdSheetRouteImport
      parentRoute: typeof AppFactionsFactionIdRoute
    }
    '/_app/factions/$factionId/edit': {
      id: '/_app/factions/$factionId/edit'
      path: '/edit'
      fullPath: '/factions/$factionId/edit'
      preLoaderRoute: typeof AppFactionsFactionIdEditRouteImport
      parentRoute: typeof AppFactionsFactionIdRoute
    }
    '/_app/rulesets/$rulesetSlug/faq/$questionSlug': {
      id: '/_app/rulesets/$rulesetSlug/faq/$questionSlug'
      path: '/rulesets/$rulesetSlug/faq/$questionSlug'
      fullPath: '/rulesets/$rulesetSlug/faq/$questionSlug'
      preLoaderRoute: typeof AppRulesetsRulesetSlugFaqQuestionSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rulesets/$id/faq/create': {
      id: '/_app/rulesets/$id/faq/create'
      path: '/faq/create'
      fullPath: '/rulesets/$id/faq/create'
      preLoaderRoute: typeof AppRulesetsIdFaqCreateRouteImport
      parentRoute: typeof AppRulesetsIdRoute
    }
  }
}

interface AppFactionsFactionIdRouteChildren {
  AppFactionsFactionIdEditRoute: typeof AppFactionsFactionIdEditRoute
  AppFactionsFactionIdSheetRoute: typeof AppFactionsFactionIdSheetRoute
}

const AppFactionsFactionIdRouteChildren: AppFactionsFactionIdRouteChildren = {
  AppFactionsFactionIdEditRoute: AppFactionsFactionIdEditRoute,
  AppFactionsFactionIdSheetRoute: AppFactionsFactionIdSheetRoute,
}

const AppFactionsFactionIdRouteWithChildren =
  AppFactionsFactionIdRoute._addFileChildren(AppFactionsFactionIdRouteChildren)

interface AppRulesetsIdRouteChildren {
  AppRulesetsIdFaqCreateRoute: typeof AppRulesetsIdFaqCreateRoute
}

const AppRulesetsIdRouteChildren: AppRulesetsIdRouteChildren = {
  AppRulesetsIdFaqCreateRoute: AppRulesetsIdFaqCreateRoute,
}

const AppRulesetsIdRouteWithChildren = AppRulesetsIdRoute._addFileChildren(
  AppRulesetsIdRouteChildren,
)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAdminMigrationsRoute: typeof AppAdminMigrationsRoute
  AppAssetsCreateRoute: typeof AppAssetsCreateRoute
  AppFactionsFactionIdRoute: typeof AppFactionsFactionIdRouteWithChildren
  AppFactionsCreateRoute: typeof AppFactionsCreateRoute
  AppFactionsMineRoute: typeof AppFactionsMineRoute
  AppGroupsCreateRoute: typeof AppGroupsCreateRoute
  AppProfilesSlugRoute: typeof AppProfilesSlugRoute
  AppProfilesSettingsRoute: typeof AppProfilesSettingsRoute
  AppRulesetsIdRoute: typeof AppRulesetsIdRouteWithChildren
  AppRulesetsCreateRoute: typeof AppRulesetsCreateRoute
  AppAssetsIndexRoute: typeof AppAssetsIndexRoute
  AppFactionsIndexRoute: typeof AppFactionsIndexRoute
  AppProfilesIndexRoute: typeof AppProfilesIndexRoute
  AppRulesetsIndexRoute: typeof AppRulesetsIndexRoute
  AppRulesetsRulesetSlugFaqQuestionSlugRoute: typeof AppRulesetsRulesetSlugFaqQuestionSlugRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAdminMigrationsRoute: AppAdminMigrationsRoute,
  AppAssetsCreateRoute: AppAssetsCreateRoute,
  AppFactionsFactionIdRoute: AppFactionsFactionIdRouteWithChildren,
  AppFactionsCreateRoute: AppFactionsCreateRoute,
  AppFactionsMineRoute: AppFactionsMineRoute,
  AppGroupsCreateRoute: AppGroupsCreateRoute,
  AppProfilesSlugRoute: AppProfilesSlugRoute,
  AppProfilesSettingsRoute: AppProfilesSettingsRoute,
  AppRulesetsIdRoute: AppRulesetsIdRouteWithChildren,
  AppRulesetsCreateRoute: AppRulesetsCreateRoute,
  AppAssetsIndexRoute: AppAssetsIndexRoute,
  AppFactionsIndexRoute: AppFactionsIndexRoute,
  AppProfilesIndexRoute: AppProfilesIndexRoute,
  AppRulesetsIndexRoute: AppRulesetsIndexRoute,
  AppRulesetsRulesetSlugFaqQuestionSlugRoute:
    AppRulesetsRulesetSlugFaqQuestionSlugRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthErrorRoute: AuthErrorRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOauthRoute: AuthOauthRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
