/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthOauthRouteImport } from './routes/auth/oauth'
import { Route as AppRulesetsIndexRouteImport } from './routes/_app/rulesets/index'
import { Route as AppProfilesIndexRouteImport } from './routes/_app/profiles/index'
import { Route as AppPrivacyIndexRouteImport } from './routes/_app/privacy/index'
import { Route as AppFactionsIndexRouteImport } from './routes/_app/factions/index'
import { Route as AppAuthIndexRouteImport } from './routes/_app/auth/index'
import { Route as AppAssetsIndexRouteImport } from './routes/_app/assets/index'
import { Route as AppRulesetsCreateRouteImport } from './routes/_app/rulesets/create'
import { Route as AppRulesetsRulesetSlugRouteImport } from './routes/_app/rulesets/$rulesetSlug'
import { Route as AppGroupsCreateRouteImport } from './routes/_app/groups/create'
import { Route as AppGroupsGroupSlugRouteImport } from './routes/_app/groups/$groupSlug'
import { Route as AppFactionsCreateRouteImport } from './routes/_app/factions/create'
import { Route as AppAuthLoginRouteImport } from './routes/_app/auth/login'
import { Route as AppAuthErrorRouteImport } from './routes/_app/auth/error'
import { Route as AppAssetsCreateRouteImport } from './routes/_app/assets/create'
import { Route as AppAdminMigrationsRouteImport } from './routes/_app/admin/migrations'
import { Route as AppRulesetsRulesetSlugIndexRouteImport } from './routes/_app/rulesets/$rulesetSlug/index'
import { Route as AppProfilesProfileSlugIndexRouteImport } from './routes/_app/profiles/$profileSlug/index'
import { Route as AppGroupsGroupSlugIndexRouteImport } from './routes/_app/groups/$groupSlug/index'
import { Route as AppFactionsFactionIdIndexRouteImport } from './routes/_app/factions/$factionId/index'
import { Route as AppRulesetsRulesetSlugEditRouteImport } from './routes/_app/rulesets/$rulesetSlug/edit'
import { Route as AppProfilesProfileSlugEditRouteImport } from './routes/_app/profiles/$profileSlug/edit'
import { Route as AppPreviewSheetFactionSlugRouteImport } from './routes/_app/preview/sheet/$factionSlug'
import { Route as AppGroupsGroupSlugEditRouteImport } from './routes/_app/groups/$groupSlug/edit'
import { Route as AppFactionsFactionIdEditRouteImport } from './routes/_app/factions/$factionId/edit'
import { Route as AppRulesetsRulesetSlugFaqCreateRouteImport } from './routes/_app/rulesets/$rulesetSlug/faq/create'
import { Route as AppRulesetsRulesetSlugFaqQuestionSlugRouteImport } from './routes/_app/rulesets/$rulesetSlug/faq/$questionSlug'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthOauthRoute = AuthOauthRouteImport.update({
  id: '/auth/oauth',
  path: '/auth/oauth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRulesetsIndexRoute = AppRulesetsIndexRouteImport.update({
  id: '/rulesets/',
  path: '/rulesets/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilesIndexRoute = AppProfilesIndexRouteImport.update({
  id: '/profiles/',
  path: '/profiles/',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivacyIndexRoute = AppPrivacyIndexRouteImport.update({
  id: '/privacy/',
  path: '/privacy/',
  getParentRoute: () => AppRoute,
} as any)
const AppFactionsIndexRoute = AppFactionsIndexRouteImport.update({
  id: '/factions/',
  path: '/factions/',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthIndexRoute = AppAuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsIndexRoute = AppAssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => AppRoute,
} as any)
const AppRulesetsCreateRoute = AppRulesetsCreateRouteImport.update({
  id: '/rulesets/create',
  path: '/rulesets/create',
  getParentRoute: () => AppRoute,
} as any)
const AppRulesetsRulesetSlugRoute = AppRulesetsRulesetSlugRouteImport.update({
  id: '/rulesets/$rulesetSlug',
  path: '/rulesets/$rulesetSlug',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsCreateRoute = AppGroupsCreateRouteImport.update({
  id: '/groups/create',
  path: '/groups/create',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsGroupSlugRoute = AppGroupsGroupSlugRouteImport.update({
  id: '/groups/$groupSlug',
  path: '/groups/$groupSlug',
  getParentRoute: () => AppRoute,
} as any)
const AppFactionsCreateRoute = AppFactionsCreateRouteImport.update({
  id: '/factions/create',
  path: '/factions/create',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthLoginRoute = AppAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthErrorRoute = AppAuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsCreateRoute = AppAssetsCreateRouteImport.update({
  id: '/assets/create',
  path: '/assets/create',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminMigrationsRoute = AppAdminMigrationsRouteImport.update({
  id: '/admin/migrations',
  path: '/admin/migrations',
  getParentRoute: () => AppRoute,
} as any)
const AppRulesetsRulesetSlugIndexRoute =
  AppRulesetsRulesetSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppRulesetsRulesetSlugRoute,
  } as any)
const AppProfilesProfileSlugIndexRoute =
  AppProfilesProfileSlugIndexRouteImport.update({
    id: '/profiles/$profileSlug/',
    path: '/profiles/$profileSlug/',
    getParentRoute: () => AppRoute,
  } as any)
const AppGroupsGroupSlugIndexRoute = AppGroupsGroupSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppGroupsGroupSlugRoute,
} as any)
const AppFactionsFactionIdIndexRoute =
  AppFactionsFactionIdIndexRouteImport.update({
    id: '/factions/$factionId/',
    path: '/factions/$factionId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppRulesetsRulesetSlugEditRoute =
  AppRulesetsRulesetSlugEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppRulesetsRulesetSlugRoute,
  } as any)
const AppProfilesProfileSlugEditRoute =
  AppProfilesProfileSlugEditRouteImport.update({
    id: '/profiles/$profileSlug/edit',
    path: '/profiles/$profileSlug/edit',
    getParentRoute: () => AppRoute,
  } as any)
const AppPreviewSheetFactionSlugRoute =
  AppPreviewSheetFactionSlugRouteImport.update({
    id: '/preview/sheet/$factionSlug',
    path: '/preview/sheet/$factionSlug',
    getParentRoute: () => AppRoute,
  } as any)
const AppGroupsGroupSlugEditRoute = AppGroupsGroupSlugEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppGroupsGroupSlugRoute,
} as any)
const AppFactionsFactionIdEditRoute =
  AppFactionsFactionIdEditRouteImport.update({
    id: '/factions/$factionId/edit',
    path: '/factions/$factionId/edit',
    getParentRoute: () => AppRoute,
  } as any)
const AppRulesetsRulesetSlugFaqCreateRoute =
  AppRulesetsRulesetSlugFaqCreateRouteImport.update({
    id: '/faq/create',
    path: '/faq/create',
    getParentRoute: () => AppRulesetsRulesetSlugRoute,
  } as any)
const AppRulesetsRulesetSlugFaqQuestionSlugRoute =
  AppRulesetsRulesetSlugFaqQuestionSlugRouteImport.update({
    id: '/faq/$questionSlug',
    path: '/faq/$questionSlug',
    getParentRoute: () => AppRulesetsRulesetSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth/oauth': typeof AuthOauthRoute
  '/admin/migrations': typeof AppAdminMigrationsRoute
  '/assets/create': typeof AppAssetsCreateRoute
  '/auth/error': typeof AppAuthErrorRoute
  '/auth/login': typeof AppAuthLoginRoute
  '/factions/create': typeof AppFactionsCreateRoute
  '/groups/$groupSlug': typeof AppGroupsGroupSlugRouteWithChildren
  '/groups/create': typeof AppGroupsCreateRoute
  '/rulesets/$rulesetSlug': typeof AppRulesetsRulesetSlugRouteWithChildren
  '/rulesets/create': typeof AppRulesetsCreateRoute
  '/assets/': typeof AppAssetsIndexRoute
  '/auth/': typeof AppAuthIndexRoute
  '/factions/': typeof AppFactionsIndexRoute
  '/privacy/': typeof AppPrivacyIndexRoute
  '/profiles/': typeof AppProfilesIndexRoute
  '/rulesets/': typeof AppRulesetsIndexRoute
  '/factions/$factionId/edit': typeof AppFactionsFactionIdEditRoute
  '/groups/$groupSlug/edit': typeof AppGroupsGroupSlugEditRoute
  '/preview/sheet/$factionSlug': typeof AppPreviewSheetFactionSlugRoute
  '/profiles/$profileSlug/edit': typeof AppProfilesProfileSlugEditRoute
  '/rulesets/$rulesetSlug/edit': typeof AppRulesetsRulesetSlugEditRoute
  '/factions/$factionId/': typeof AppFactionsFactionIdIndexRoute
  '/groups/$groupSlug/': typeof AppGroupsGroupSlugIndexRoute
  '/profiles/$profileSlug/': typeof AppProfilesProfileSlugIndexRoute
  '/rulesets/$rulesetSlug/': typeof AppRulesetsRulesetSlugIndexRoute
  '/rulesets/$rulesetSlug/faq/$questionSlug': typeof AppRulesetsRulesetSlugFaqQuestionSlugRoute
  '/rulesets/$rulesetSlug/faq/create': typeof AppRulesetsRulesetSlugFaqCreateRoute
}
export interface FileRoutesByTo {
  '/auth/oauth': typeof AuthOauthRoute
  '/': typeof AppIndexRoute
  '/admin/migrations': typeof AppAdminMigrationsRoute
  '/assets/create': typeof AppAssetsCreateRoute
  '/auth/error': typeof AppAuthErrorRoute
  '/auth/login': typeof AppAuthLoginRoute
  '/factions/create': typeof AppFactionsCreateRoute
  '/groups/create': typeof AppGroupsCreateRoute
  '/rulesets/create': typeof AppRulesetsCreateRoute
  '/assets': typeof AppAssetsIndexRoute
  '/auth': typeof AppAuthIndexRoute
  '/factions': typeof AppFactionsIndexRoute
  '/privacy': typeof AppPrivacyIndexRoute
  '/profiles': typeof AppProfilesIndexRoute
  '/rulesets': typeof AppRulesetsIndexRoute
  '/factions/$factionId/edit': typeof AppFactionsFactionIdEditRoute
  '/groups/$groupSlug/edit': typeof AppGroupsGroupSlugEditRoute
  '/preview/sheet/$factionSlug': typeof AppPreviewSheetFactionSlugRoute
  '/profiles/$profileSlug/edit': typeof AppProfilesProfileSlugEditRoute
  '/rulesets/$rulesetSlug/edit': typeof AppRulesetsRulesetSlugEditRoute
  '/factions/$factionId': typeof AppFactionsFactionIdIndexRoute
  '/groups/$groupSlug': typeof AppGroupsGroupSlugIndexRoute
  '/profiles/$profileSlug': typeof AppProfilesProfileSlugIndexRoute
  '/rulesets/$rulesetSlug': typeof AppRulesetsRulesetSlugIndexRoute
  '/rulesets/$rulesetSlug/faq/$questionSlug': typeof AppRulesetsRulesetSlugFaqQuestionSlugRoute
  '/rulesets/$rulesetSlug/faq/create': typeof AppRulesetsRulesetSlugFaqCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth/oauth': typeof AuthOauthRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/migrations': typeof AppAdminMigrationsRoute
  '/_app/assets/create': typeof AppAssetsCreateRoute
  '/_app/auth/error': typeof AppAuthErrorRoute
  '/_app/auth/login': typeof AppAuthLoginRoute
  '/_app/factions/create': typeof AppFactionsCreateRoute
  '/_app/groups/$groupSlug': typeof AppGroupsGroupSlugRouteWithChildren
  '/_app/groups/create': typeof AppGroupsCreateRoute
  '/_app/rulesets/$rulesetSlug': typeof AppRulesetsRulesetSlugRouteWithChildren
  '/_app/rulesets/create': typeof AppRulesetsCreateRoute
  '/_app/assets/': typeof AppAssetsIndexRoute
  '/_app/auth/': typeof AppAuthIndexRoute
  '/_app/factions/': typeof AppFactionsIndexRoute
  '/_app/privacy/': typeof AppPrivacyIndexRoute
  '/_app/profiles/': typeof AppProfilesIndexRoute
  '/_app/rulesets/': typeof AppRulesetsIndexRoute
  '/_app/factions/$factionId/edit': typeof AppFactionsFactionIdEditRoute
  '/_app/groups/$groupSlug/edit': typeof AppGroupsGroupSlugEditRoute
  '/_app/preview/sheet/$factionSlug': typeof AppPreviewSheetFactionSlugRoute
  '/_app/profiles/$profileSlug/edit': typeof AppProfilesProfileSlugEditRoute
  '/_app/rulesets/$rulesetSlug/edit': typeof AppRulesetsRulesetSlugEditRoute
  '/_app/factions/$factionId/': typeof AppFactionsFactionIdIndexRoute
  '/_app/groups/$groupSlug/': typeof AppGroupsGroupSlugIndexRoute
  '/_app/profiles/$profileSlug/': typeof AppProfilesProfileSlugIndexRoute
  '/_app/rulesets/$rulesetSlug/': typeof AppRulesetsRulesetSlugIndexRoute
  '/_app/rulesets/$rulesetSlug/faq/$questionSlug': typeof AppRulesetsRulesetSlugFaqQuestionSlugRoute
  '/_app/rulesets/$rulesetSlug/faq/create': typeof AppRulesetsRulesetSlugFaqCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/oauth'
    | '/admin/migrations'
    | '/assets/create'
    | '/auth/error'
    | '/auth/login'
    | '/factions/create'
    | '/groups/$groupSlug'
    | '/groups/create'
    | '/rulesets/$rulesetSlug'
    | '/rulesets/create'
    | '/assets/'
    | '/auth/'
    | '/factions/'
    | '/privacy/'
    | '/profiles/'
    | '/rulesets/'
    | '/factions/$factionId/edit'
    | '/groups/$groupSlug/edit'
    | '/preview/sheet/$factionSlug'
    | '/profiles/$profileSlug/edit'
    | '/rulesets/$rulesetSlug/edit'
    | '/factions/$factionId/'
    | '/groups/$groupSlug/'
    | '/profiles/$profileSlug/'
    | '/rulesets/$rulesetSlug/'
    | '/rulesets/$rulesetSlug/faq/$questionSlug'
    | '/rulesets/$rulesetSlug/faq/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/oauth'
    | '/'
    | '/admin/migrations'
    | '/assets/create'
    | '/auth/error'
    | '/auth/login'
    | '/factions/create'
    | '/groups/create'
    | '/rulesets/create'
    | '/assets'
    | '/auth'
    | '/factions'
    | '/privacy'
    | '/profiles'
    | '/rulesets'
    | '/factions/$factionId/edit'
    | '/groups/$groupSlug/edit'
    | '/preview/sheet/$factionSlug'
    | '/profiles/$profileSlug/edit'
    | '/rulesets/$rulesetSlug/edit'
    | '/factions/$factionId'
    | '/groups/$groupSlug'
    | '/profiles/$profileSlug'
    | '/rulesets/$rulesetSlug'
    | '/rulesets/$rulesetSlug/faq/$questionSlug'
    | '/rulesets/$rulesetSlug/faq/create'
  id:
    | '__root__'
    | '/_app'
    | '/auth/oauth'
    | '/_app/'
    | '/_app/admin/migrations'
    | '/_app/assets/create'
    | '/_app/auth/error'
    | '/_app/auth/login'
    | '/_app/factions/create'
    | '/_app/groups/$groupSlug'
    | '/_app/groups/create'
    | '/_app/rulesets/$rulesetSlug'
    | '/_app/rulesets/create'
    | '/_app/assets/'
    | '/_app/auth/'
    | '/_app/factions/'
    | '/_app/privacy/'
    | '/_app/profiles/'
    | '/_app/rulesets/'
    | '/_app/factions/$factionId/edit'
    | '/_app/groups/$groupSlug/edit'
    | '/_app/preview/sheet/$factionSlug'
    | '/_app/profiles/$profileSlug/edit'
    | '/_app/rulesets/$rulesetSlug/edit'
    | '/_app/factions/$factionId/'
    | '/_app/groups/$groupSlug/'
    | '/_app/profiles/$profileSlug/'
    | '/_app/rulesets/$rulesetSlug/'
    | '/_app/rulesets/$rulesetSlug/faq/$questionSlug'
    | '/_app/rulesets/$rulesetSlug/faq/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthOauthRoute: typeof AuthOauthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/oauth': {
      id: '/auth/oauth'
      path: '/auth/oauth'
      fullPath: '/auth/oauth'
      preLoaderRoute: typeof AuthOauthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/rulesets/': {
      id: '/_app/rulesets/'
      path: '/rulesets'
      fullPath: '/rulesets/'
      preLoaderRoute: typeof AppRulesetsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profiles/': {
      id: '/_app/profiles/'
      path: '/profiles'
      fullPath: '/profiles/'
      preLoaderRoute: typeof AppProfilesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/privacy/': {
      id: '/_app/privacy/'
      path: '/privacy'
      fullPath: '/privacy/'
      preLoaderRoute: typeof AppPrivacyIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/factions/': {
      id: '/_app/factions/'
      path: '/factions'
      fullPath: '/factions/'
      preLoaderRoute: typeof AppFactionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/': {
      id: '/_app/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AppAuthIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets/': {
      id: '/_app/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AppAssetsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rulesets/create': {
      id: '/_app/rulesets/create'
      path: '/rulesets/create'
      fullPath: '/rulesets/create'
      preLoaderRoute: typeof AppRulesetsCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rulesets/$rulesetSlug': {
      id: '/_app/rulesets/$rulesetSlug'
      path: '/rulesets/$rulesetSlug'
      fullPath: '/rulesets/$rulesetSlug'
      preLoaderRoute: typeof AppRulesetsRulesetSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/create': {
      id: '/_app/groups/create'
      path: '/groups/create'
      fullPath: '/groups/create'
      preLoaderRoute: typeof AppGroupsCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/$groupSlug': {
      id: '/_app/groups/$groupSlug'
      path: '/groups/$groupSlug'
      fullPath: '/groups/$groupSlug'
      preLoaderRoute: typeof AppGroupsGroupSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/factions/create': {
      id: '/_app/factions/create'
      path: '/factions/create'
      fullPath: '/factions/create'
      preLoaderRoute: typeof AppFactionsCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/login': {
      id: '/_app/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AppAuthLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/error': {
      id: '/_app/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AppAuthErrorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets/create': {
      id: '/_app/assets/create'
      path: '/assets/create'
      fullPath: '/assets/create'
      preLoaderRoute: typeof AppAssetsCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/migrations': {
      id: '/_app/admin/migrations'
      path: '/admin/migrations'
      fullPath: '/admin/migrations'
      preLoaderRoute: typeof AppAdminMigrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rulesets/$rulesetSlug/': {
      id: '/_app/rulesets/$rulesetSlug/'
      path: '/'
      fullPath: '/rulesets/$rulesetSlug/'
      preLoaderRoute: typeof AppRulesetsRulesetSlugIndexRouteImport
      parentRoute: typeof AppRulesetsRulesetSlugRoute
    }
    '/_app/profiles/$profileSlug/': {
      id: '/_app/profiles/$profileSlug/'
      path: '/profiles/$profileSlug'
      fullPath: '/profiles/$profileSlug/'
      preLoaderRoute: typeof AppProfilesProfileSlugIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/$groupSlug/': {
      id: '/_app/groups/$groupSlug/'
      path: '/'
      fullPath: '/groups/$groupSlug/'
      preLoaderRoute: typeof AppGroupsGroupSlugIndexRouteImport
      parentRoute: typeof AppGroupsGroupSlugRoute
    }
    '/_app/factions/$factionId/': {
      id: '/_app/factions/$factionId/'
      path: '/factions/$factionId'
      fullPath: '/factions/$factionId/'
      preLoaderRoute: typeof AppFactionsFactionIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rulesets/$rulesetSlug/edit': {
      id: '/_app/rulesets/$rulesetSlug/edit'
      path: '/edit'
      fullPath: '/rulesets/$rulesetSlug/edit'
      preLoaderRoute: typeof AppRulesetsRulesetSlugEditRouteImport
      parentRoute: typeof AppRulesetsRulesetSlugRoute
    }
    '/_app/profiles/$profileSlug/edit': {
      id: '/_app/profiles/$profileSlug/edit'
      path: '/profiles/$profileSlug/edit'
      fullPath: '/profiles/$profileSlug/edit'
      preLoaderRoute: typeof AppProfilesProfileSlugEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/preview/sheet/$factionSlug': {
      id: '/_app/preview/sheet/$factionSlug'
      path: '/preview/sheet/$factionSlug'
      fullPath: '/preview/sheet/$factionSlug'
      preLoaderRoute: typeof AppPreviewSheetFactionSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/$groupSlug/edit': {
      id: '/_app/groups/$groupSlug/edit'
      path: '/edit'
      fullPath: '/groups/$groupSlug/edit'
      preLoaderRoute: typeof AppGroupsGroupSlugEditRouteImport
      parentRoute: typeof AppGroupsGroupSlugRoute
    }
    '/_app/factions/$factionId/edit': {
      id: '/_app/factions/$factionId/edit'
      path: '/factions/$factionId/edit'
      fullPath: '/factions/$factionId/edit'
      preLoaderRoute: typeof AppFactionsFactionIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rulesets/$rulesetSlug/faq/create': {
      id: '/_app/rulesets/$rulesetSlug/faq/create'
      path: '/faq/create'
      fullPath: '/rulesets/$rulesetSlug/faq/create'
      preLoaderRoute: typeof AppRulesetsRulesetSlugFaqCreateRouteImport
      parentRoute: typeof AppRulesetsRulesetSlugRoute
    }
    '/_app/rulesets/$rulesetSlug/faq/$questionSlug': {
      id: '/_app/rulesets/$rulesetSlug/faq/$questionSlug'
      path: '/faq/$questionSlug'
      fullPath: '/rulesets/$rulesetSlug/faq/$questionSlug'
      preLoaderRoute: typeof AppRulesetsRulesetSlugFaqQuestionSlugRouteImport
      parentRoute: typeof AppRulesetsRulesetSlugRoute
    }
  }
}

interface AppGroupsGroupSlugRouteChildren {
  AppGroupsGroupSlugEditRoute: typeof AppGroupsGroupSlugEditRoute
  AppGroupsGroupSlugIndexRoute: typeof AppGroupsGroupSlugIndexRoute
}

const AppGroupsGroupSlugRouteChildren: AppGroupsGroupSlugRouteChildren = {
  AppGroupsGroupSlugEditRoute: AppGroupsGroupSlugEditRoute,
  AppGroupsGroupSlugIndexRoute: AppGroupsGroupSlugIndexRoute,
}

const AppGroupsGroupSlugRouteWithChildren =
  AppGroupsGroupSlugRoute._addFileChildren(AppGroupsGroupSlugRouteChildren)

interface AppRulesetsRulesetSlugRouteChildren {
  AppRulesetsRulesetSlugEditRoute: typeof AppRulesetsRulesetSlugEditRoute
  AppRulesetsRulesetSlugIndexRoute: typeof AppRulesetsRulesetSlugIndexRoute
  AppRulesetsRulesetSlugFaqQuestionSlugRoute: typeof AppRulesetsRulesetSlugFaqQuestionSlugRoute
  AppRulesetsRulesetSlugFaqCreateRoute: typeof AppRulesetsRulesetSlugFaqCreateRoute
}

const AppRulesetsRulesetSlugRouteChildren: AppRulesetsRulesetSlugRouteChildren =
  {
    AppRulesetsRulesetSlugEditRoute: AppRulesetsRulesetSlugEditRoute,
    AppRulesetsRulesetSlugIndexRoute: AppRulesetsRulesetSlugIndexRoute,
    AppRulesetsRulesetSlugFaqQuestionSlugRoute:
      AppRulesetsRulesetSlugFaqQuestionSlugRoute,
    AppRulesetsRulesetSlugFaqCreateRoute: AppRulesetsRulesetSlugFaqCreateRoute,
  }

const AppRulesetsRulesetSlugRouteWithChildren =
  AppRulesetsRulesetSlugRoute._addFileChildren(
    AppRulesetsRulesetSlugRouteChildren,
  )

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAdminMigrationsRoute: typeof AppAdminMigrationsRoute
  AppAssetsCreateRoute: typeof AppAssetsCreateRoute
  AppAuthErrorRoute: typeof AppAuthErrorRoute
  AppAuthLoginRoute: typeof AppAuthLoginRoute
  AppFactionsCreateRoute: typeof AppFactionsCreateRoute
  AppGroupsGroupSlugRoute: typeof AppGroupsGroupSlugRouteWithChildren
  AppGroupsCreateRoute: typeof AppGroupsCreateRoute
  AppRulesetsRulesetSlugRoute: typeof AppRulesetsRulesetSlugRouteWithChildren
  AppRulesetsCreateRoute: typeof AppRulesetsCreateRoute
  AppAssetsIndexRoute: typeof AppAssetsIndexRoute
  AppAuthIndexRoute: typeof AppAuthIndexRoute
  AppFactionsIndexRoute: typeof AppFactionsIndexRoute
  AppPrivacyIndexRoute: typeof AppPrivacyIndexRoute
  AppProfilesIndexRoute: typeof AppProfilesIndexRoute
  AppRulesetsIndexRoute: typeof AppRulesetsIndexRoute
  AppFactionsFactionIdEditRoute: typeof AppFactionsFactionIdEditRoute
  AppPreviewSheetFactionSlugRoute: typeof AppPreviewSheetFactionSlugRoute
  AppProfilesProfileSlugEditRoute: typeof AppProfilesProfileSlugEditRoute
  AppFactionsFactionIdIndexRoute: typeof AppFactionsFactionIdIndexRoute
  AppProfilesProfileSlugIndexRoute: typeof AppProfilesProfileSlugIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAdminMigrationsRoute: AppAdminMigrationsRoute,
  AppAssetsCreateRoute: AppAssetsCreateRoute,
  AppAuthErrorRoute: AppAuthErrorRoute,
  AppAuthLoginRoute: AppAuthLoginRoute,
  AppFactionsCreateRoute: AppFactionsCreateRoute,
  AppGroupsGroupSlugRoute: AppGroupsGroupSlugRouteWithChildren,
  AppGroupsCreateRoute: AppGroupsCreateRoute,
  AppRulesetsRulesetSlugRoute: AppRulesetsRulesetSlugRouteWithChildren,
  AppRulesetsCreateRoute: AppRulesetsCreateRoute,
  AppAssetsIndexRoute: AppAssetsIndexRoute,
  AppAuthIndexRoute: AppAuthIndexRoute,
  AppFactionsIndexRoute: AppFactionsIndexRoute,
  AppPrivacyIndexRoute: AppPrivacyIndexRoute,
  AppProfilesIndexRoute: AppProfilesIndexRoute,
  AppRulesetsIndexRoute: AppRulesetsIndexRoute,
  AppFactionsFactionIdEditRoute: AppFactionsFactionIdEditRoute,
  AppPreviewSheetFactionSlugRoute: AppPreviewSheetFactionSlugRoute,
  AppProfilesProfileSlugEditRoute: AppProfilesProfileSlugEditRoute,
  AppFactionsFactionIdIndexRoute: AppFactionsFactionIdIndexRoute,
  AppProfilesProfileSlugIndexRoute: AppProfilesProfileSlugIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthOauthRoute: AuthOauthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
